// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm8UATZgyx8pbguEs9b4DPar7l6hZKeHo',
    appId: '1:974001658618:web:2b3382363adf7348f28743',
    messagingSenderId: '974001658618',
    projectId: 'smart-meal-planner-app-4556',
    authDomain: 'smart-meal-planner-app-4556.firebaseapp.com',
    storageBucket: 'smart-meal-planner-app-4556.firebasestorage.app',
    measurementId: 'G-M9N9V0RG9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo7XzIRBHrXiXBXcOUq0eJfkCPpwpfYOM',
    appId: '1:974001658618:android:d01cac90a77fb6fdf28743',
    messagingSenderId: '974001658618',
    projectId: 'smart-meal-planner-app-4556',
    storageBucket: 'smart-meal-planner-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklubnvMWF7T2DPazvmiK6DJebpkL2SIY',
    appId: '1:974001658618:ios:23c9bd542390bb97f28743',
    messagingSenderId: '974001658618',
    projectId: 'smart-meal-planner-app-4556',
    storageBucket: 'smart-meal-planner-app-4556.firebasestorage.app',
    iosBundleId: 'com.microcode.mealPlannerApp',
  );
}
